apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dbay-ingress
  namespace: dbay
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  rules:
    - http:
        paths:
          - path: /api/v1/listings
            pathType: Prefix
            backend:
              service:
                name: listing-service
                port:
                  number: 8001
          - path: /api/v1/auctions
            pathType: Prefix
            backend:
              service:
                name: auction-service
                port:
                  number: 8002
          - path: /api/v1/wallet
            pathType: Prefix
            backend:
              service:
                name: wallet-service
                port:
                  number: 8003
          # ... add other services
